### ISSUE TITLE
API call is is causing Homebridge restart

### ISSUE THREAD

**Issue by sbernhardt81** [Tommrodrigues/homebridge-web-motion#3]
While testing the API I see it is causing an homebridge (v1.3.2) restart:

$curl  -d 'id=bath-floorheat-on&value=0' http://homebridge:2000/motionDetected 
HTTP/1.1 200 OK
Date: Sun, 21 Mar 2021 18:09:48 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Content-Length: 16

Handling request

[3/21/2021, 7:09:48 PM] TypeError: Cannot read property 'setState' of undefined
    at WebMotion._httpHandler (/usr/local/lib/node_modules/homebridge-web-motion/index.js:60:36)
    at WebMotion.<anonymous> (/usr/local/lib/node_modules/homebridge-web-motion/index.js:31:12)
    at Server.emit (events.js:315:20)
    at parserOnIncoming (_http_server.js:874:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
[3/21/2021, 7:09:48 PM] Got SIGTERM, shutting down Homebridge...

Config:
{
    "platform": "WebMotion",
    "name": "WebMotion",
    "autoReset": "false",
    "autoResetDelay": "5",
    "sensors": [
        {
            "name": "Heizung Bad an",
            "id": "bath-floorheat-on"
        },
        {
            "name": "Heizung Bad aus",
            "id": "bath-floorheat-off"
        },
        {
            "name": "Heizung WZ an",
            "id": "living-floorheat-on"
        },
        {
            "name": "Heizung WZ aus",
            "id": "living-floorheat-off"
        }
    ]
}

**Comment by phenotypic** [comment]
Hi there, you are having this problem because of your `curl` command. I have tested the plugin with your `config.json` and it crashes when you use the `curl` command you provided (`curl -d 'id=bath-floorheat-on&value=0' http://homebridge:2000/motionDetected`).

Instead please use a `curl` command formatted like this to resolve the issue:

```
curl 'http://homebridge:2000/motionDetected?id=bath-floorheat-on&value=1'
```
